### ISSUE TITLE
baseline_zero bugs

### ISSUE THREAD

**Issue by jbouzanquet** [CSULA-Qdots/filter#10]
- [x] Line 6 of baseline_zero appears to transform list_names from a string array to a string. Is matlab weakly-typed? Could that possibly be why it didn't work when trying to run over multiple files simultaneously?
- [x] I know I named the program baseline_zero, but that turns out to be annoying to type. Thoughts on a better time? Would simple "zero" be better?
- [x] Variable names should be understandable to future readers, and some are entirely arbitrary, like the function "dissect" and it's input "fame". Refactoring these should be simple with a replace all command in the text editor.
- [x] Go through code and fix areas marked with the comment ???

**Comment by blackdjinn** [comment]
"zero" would be better, IMHO. or 'subtract_background' or... lots of things.

**Comment by aachew2008** [comment]
list_names = list_names{1} is used to transform list_names from a cell to an array. The textscan command spits out an array of strings, but that array is stored in the first cell of a cell array. I redefine list_names to be the array itself, instead of a cell containing the array.

As for the "not working" part, is the program not working? It should be - I tested it.

**Comment by jbouzanquet** [comment]
Oh right, it only failed on a command line, not within matlab. I'm making some changes to the program right now. I'll push my commits so you can see. I'm still working on it, but I'm close to done with what I plan to do right now.

**Comment by aachew2008** [comment]
Has the shell program been written that calls the zeroing program?

**Comment by jbouzanquet** [comment]
We tried, it doesn't work from shell. The way shell transmits arguments is too different from matlab. It should be possible with more control, but that will require python or tcl or something. I believe Ryan said he'd make that at some point. Check out my fresh commit, read everything marked %???. That's where you have to make changes or delete my comment and explain why here.

**Comment by aachew2008** [comment]
I committed it.
None of the functions are recursive, btw.

**Comment by jbouzanquet** [comment]
Don't forget to push. A commit happens on your machine, pushing sends it upstream.

**Comment by jbouzanquet** [comment]
If you took care of all the questions in the file you can mark the check box in the first comment and close this issue. Also look at how the checkmarks work, that's neat for these things.
