### ISSUE TITLE
Request review of  pmt_scaling_integration branch

### ISSUE THREAD

**Issue by jbouzanquet** [CSULA-Qdots/filter#11]
I made a branch for modifications to filter.tcl that I think should integrate the functionality of rescale.tcl with a command line parameter, 
`$tclsh filter.tcl --pmt file.dat`
Since I can't actually write tcl and did that by copying other lines in the program and editing them, I'd like you to check whether it works. If it does should I merge it with master, or leave it until you've merged your laser detect branch?
Unfortunately a diff with the current branch will show nearly every line changed because I screwed up indentation and used an automated indenter, but a diff with commit  e860546287308bbfb9ebed92a0f7bae90556a9b2 should be reasonable.

**Comment by aachew2008** [comment]
Hey,
I did some digging and I found a way to get all the *_eV.out.dat files into an array in shell. All we need now is a for loop that will call matlab for each element (turned into a string). I can't get matlab to work in command line; could you finish the rest of the program?
-Aaron

**Comment by blackdjinn** [comment]
Yeah, that's not gonna work as written. I see what you're wanting, and it's going to require a bit more logic to parse ARGV properly. Also, the stuff in 'output' is just plain wonky. Don't try running it... it might not run and will produce garbage.

**Comment by jbouzanquet** [comment]
I haven't changed it since I don't really understand the language. I think making it an option is superior to a separate program to run, and hopefully not too hard to implement. Any progress on the laser detect logic?

**Comment by blackdjinn** [comment]
Getting there. I've finally managed to recover from a massive computer failure (dead laptop mobo) to the point I can actually get some work done.

**Comment by jbouzanquet** [comment]
Damn. Didn't know that, too bad you didn't email about it from phone or something. I could probably have lent use of the spare computer from my house.

**Comment by blackdjinn** [comment]
Needed a laptop with enough screen real-estate to work on it. Coding on a netbook is... difficult. No place to set up a desktop machine here.

Getting this working right is the next feature I'm putting in. I'll merge it with mainline once that's done and close.

**Comment by blackdjinn** [comment]
This is done, AFAIK
