### ISSUE TITLE
Return Codes

### ISSUE THREAD

**Issue by jbouzanquet** [CSULA-Qdots/filter#17]
Right now MCP just plows on through steps whatever happens or doesn't happen in previous steps. If we added return codes, even just a generic code 1 means don't continue, then it could know to stop and avoid cluttering up a cli when you just want to read the first error. 
I haven't used such codes in shell before, is my commented out example on line 20 of MCP correct?

**Comment by blackdjinn** [comment]
Filter has IIRC only one fatal error condition, but I can have it return an exit code on that... The code catches most operator errors and chugs on. Tclsh will return an error code on an actual error.

If you are trying to avoid screen spam, I can add an option to suppress echoing log stuff to STDOUT.

**Comment by blackdjinn** [comment]
Oh... and I'll look at your MCP thing...

**Comment by blackdjinn** [comment]
Can we even /get/ error codes from MATLAB stuff?

**Comment by jbouzanquet** [comment]
I don't think we can. The file matlab, the one you invoke to start the environment and that our scripts start with redirected input, is actually a wrapper. The executable that controls the interface, and presumably performs or launches mathematical evaluation, is MATLAB. And although I'm not entirely sure, I think matlab may close before MATLAB.

**Comment by blackdjinn** [comment]
Since the rest of this isn't going to be implemented... Closing this as fixed in mainline.
