### ISSUE TITLE
Implement zeroing based on background run

### ISSUE THREAD

**Issue by jbouzanquet** [CSULA-Qdots/filter#2]
There should be a version of filter or standalone script that subtracts a baseline from the data calibrated to a background material run.

**Comment by blackdjinn** [comment]
Subtracting baseline values would be possible. Tho that begs the question of just what that 'zero' is. Do we have enough control over variables to do that?

**Comment by jbouzanquet** [comment]
Have you called or chatted with the people in lab right now? I believe they wanted to adjust to fit two points on a curve they're measuring today.

**Comment by aachew2008** [comment]
I've got the basic code written for that. We've run the GaAs wafer again and fit it with a quadratic curve. We then "callibrate" the curve by picking two points in our signal and subtracting out a modified background curve. It seems to work well for smooth data but if there's a lot of noise, the signal dips into the negatives after callibration.

**Comment by aachew2008** [comment]
![Fixed](https://f.cloud.github.com/assets/3516502/141786/87b6ff96-7270-11e2-8098-ba24f9ba0988.png)

A "zeroed" graph that worked

**Comment by aachew2008** [comment]
![Fixed2](https://f.cloud.github.com/assets/3516502/141789/e3effefc-7270-11e2-8e5a-6db197e4656f.png)

This didn't work so well

**Comment by aachew2008** [comment]
Just finished modifying the program to take averages at its callibration points. It should work better now.

**Comment by jbouzanquet** [comment]
How many points included in the average?

**Comment by aachew2008** [comment]
5.

**Comment by jbouzanquet** [comment]
This bug is about implementation. That's done, and though the program still needs work I'll close this issue and open another for bug work.
