### ISSUE TITLE
Implement logic to exclude second order peak for each laser

### ISSUE THREAD

**Issue by jbouzanquet** [CSULA-Qdots/filter#4]
The area to exclude varies by color, which is communicated within the filename. There could be a hardcoded table of names and ranges, or it could read from the filterrc. This change will require renaming all existing files of green 20 mW data to include an explicit laser color in the filename.

**Comment by blackdjinn** [comment]
Soft configuring it will be more useful in the long run and about as much work. I'll set it up so.

**Comment by jbouzanquet** [comment]
I suppose I'll start renaming data then. And deleting the filtered data under the old names. This will take a bit.

**Comment by blackdjinn** [comment]
OK. I'll get the hooks in.

**Comment by jbouzanquet** [comment]
The example.filterrc will need updating with the table of laser names and second orders. Not sure how you want it formatted, but for example

> 5G 10500 10700
> 20G 10500 10700

Don't recall the values needed for the 5V, 5R, and RMG lasers. If it encounters one without a laser name it recognizes it should likely ignore that, which takes care of the white light runs we tried and generally avoids destroying data.

**Comment by blackdjinn** [comment]
Command line options have been added on branch rd.laseroption

git fetch --all
git checkout rd.laseroption

and you'll be able to test it. Look at README.md for docs on it.

**Comment by jbouzanquet** [comment]
Okay, I decided to test this before merging the branches, and the green result is the same, but red isn't. The log indicates that it is in the red logic branch, but the file still comes out cut at 10300. I can't figure out what's happening. Partial log pasted below

```
$ ./filter.tcl --laser=red G5-RMG-201305*
123432 : log starting at 20130602123432
123432 : config file: D:\bin\cygwin\home\Julian\.filterrc2
123432 : reading configuration from ~/.filterrc2
123432 : Parsing command line.
123432 : ARGV:
123432 : --laser=red G5-RMG-20130524-3.dat G5-RMG-20130530-1.dat
123432 : Element: --laser=red
123432 : setoption: --laser=red
123432 : Commandline, setting laser to red
123432 : Element: G5-RMG-20130524-3.dat
123432 : Element: G5-RMG-20130530-1.dat
123432 : Files: G5-RMG-20130524-3.dat G5-RMG-20130530-1.dat
123432 : Using laser: Red
123432 : --
```

File begins

```
rescaled! delta:10 thresh:0.10 G5, RMG Io 88.8  w Splitter, 10-2 avg, 77k, Run 1    date: 5/30/2013 time:  1:08 PM
ev      lockin sr510    dmm kiethley 199
1.204607141122  0.000157684493  0.004583099857
1.205485561497  0.000156328554  0.004583099857
```

Which is a starting wavelength of [10300 A](https://www.wolframalpha.com/input/?i=wavelength+of+1.204607141122+eV+photon).  But output from filter_red starts at [11500 A](https://www.wolframalpha.com/input/?i=wavelength+of+1.078123391304+eV+photon)

```
$ ./filter_red.tcl G5-RMG-201305*
124800 : log starting at 20130602124800
124800 : config file: D:\bin\cygwin\home\Julian\.filterrc2
124800 : reading configuration from ~/.filterrc2
124800 : Parsing command line.
124800 : ARGV:
124800 : G5-RMG-20130524-3.dat G5-RMG-20130530-1.dat
124800 : Element: G5-RMG-20130524-3.dat
124800 : Element: G5-RMG-20130530-1.dat
124800 : Files: G5-RMG-20130524-3.dat G5-RMG-20130530-1.dat
124800 : --
```

Here's the data put out by filter_red.

```
rescaled! delta:10 thresh:0.10 G5, RMG Io 88.8  w Splitter, 10-2 avg, 77k, Run 1    date: 5/30/2013 time:  1:08 PM
ev      lockin sr510    dmm kiethley 199
1.078123391304  0.000368500975  0.004580900073
1.078826974114  0.000379049504  0.004581300076
```

Output from green option vs filter_green was identical by comparison of md5s.
