### ISSUE TITLE
Making a Program that will call the Different data processing programs

### ISSUE THREAD

**Issue by aachew2008** [CSULA-Qdots/filter#5]
From what I understand, It seems like our data analysis goes through 5 parts:
Step 1: Filter data. (Filtering program)
- This must come first, as we have to get rid of the second order peak.

Step 2: Smooth data. ??? (Is there a smoothing program??)
- This must come before zeroing the data; We callibrate our background signal using two points of the original signal.
  If we land on a sharp peak or a trough when picking these points, we will get a large negative signal.

Step 3: Zero data. (Zeroing program)
- This is done with the background signal of the GaAs wafer. A quadratic fit was used to model this data:
  y = 0.0015873240642803 - 0.00000025667991263308_r +0.000000000011008884166353_r*r
  r is the wavelength, and y is the signal.

Step 4: Fit data. (IPF)
- We use equal-width Gaussians with NO autozeroing (it's been taken care of by the zeroing program in the previous step).
  We fit 4 peaks and generate a list of results, which we put in a spreadsheet.

Step 5: Bin the data. (Histogram)
- This is easy.

It would be good if we could combine the first 3 programs together, as they can be fully automated.

**Comment by jbouzanquet** [comment]
filter.tcl smooths the data by deleting points far from average. To be more specific, your step one is removing second order. From out chat it sounds like you aren't sure whether smooth or zero should come first. So we want either
1. Second order removal, considerate of laser used
2. Zeroing based on fitting one or two points to background run
3. Smoothing with existing averaging filter
4. Manual steps
or 
1. Second order
2. Smoothing
3. Zeroing
4. Manual

**Comment by blackdjinn** [comment]
Yeah. What 'filter' does is reject outliers. So... it doesn't /smooth/ the data so much as drop points that seem to be noise. But.... This refactoring makes a certain amount of sense if we want to talk over the entire process and code from scratch.

**Comment by blackdjinn** [comment]
Also the goal here... is it a command-line program that operates in batch-mode like Filter does or are we aiming at something that has some kind of GUI console? I'd /really/ like to avoid GUI coding for this...

**Comment by jbouzanquet** [comment]
Bleh. Command line is fine for me and you, but that paltry thing called a console in windows is quite hard to deal with. It doesn't have much of the easy globbing and tab completions of a nix command line. I think a cli program should be the goal, but perhaps with an eye to eventually building a simple gui. As simple as just a list of files in a directory with the ability to checkmark ones to run.

**Comment by jbouzanquet** [comment]
Relevant to our automation interests:
http://stackoverflow.com/questions/2001183/how-to-call-matlab-functions-from-the-linux-command-line
I used 
`$ ./matlab_batcher.sh baseline_zero \'file.out\'`
sucessfully. There are other ways of calling matlab, but this one didn't royally screw up my terminal afterwards. The other methods might work better if the "exit" command were placed at the end of all .m programs we use.
Aaron is trying to get baseline_zero.m to support multiple filenames in the argument, which will allow the command above to work on all the data with a simple glob.
`$ ./matlab_batcher.sh baseline_zero \'*eV.out.dat\'`

**Comment by jbouzanquet** [comment]
From Skype conversation: 
1. raw
2. zero
3. scale
- If we decide to PMT sensitivity scale
  1. noise-reject
  2. ipf

Can somebody figure out what's happening to Markdown above?

**Comment by blackdjinn** [comment]
This looks like its been done. Close?

**Comment by jbouzanquet** [comment]
Yeah. Not perfect but MCP does it I guess. Closing
