### ISSUE TITLE
More projects

### ISSUE THREAD

**Issue by blackdjinn** [CSULA-Qdots/filter#6]
Should we put 'baseline zero' and our curve fitting routine into their own projects? Would kind of make sense at least for now.

**Comment by jbouzanquet** [comment]
I don't see the need really. They may be logically different, but each is so small that it would just make more work by having to manage multiple projects. The software will probably all be controlled by one program later on anyway.

**Comment by blackdjinn** [comment]
This is true.

**Comment by blackdjinn** [comment]
Closing.
