### ISSUE TITLE
Omit rescale.tcl

### ISSUE THREAD

**Issue by blackdjinn** [CSULA-Qdots/filter#7]
It seems to have been written to try and adjust for the PMT sensitivity from RCA. It also seems broken. My memory says we were rejecting it because it made stuff look wrong.

**Comment by jbouzanquet** [comment]
I don't think it's broken so much as its not something we should do to the data. It did make things look quite strange. Which reminds me, we should look at what happens when it's run on data before or after baseline_zero

**Comment by blackdjinn** [comment]
.... We totally should.

**Comment by jbouzanquet** [comment]
Closing issue as we can't delete until futther testing
